apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app01
  template:
    metadata:
      labels:
        app: my-app01
    spec:
      containers:
      - name: my-app01
        image: filstimatias/gitops-goapp:8568ca149ab941abdce5f845cfd2dff4715cb1c0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"