apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: http-service-check
  namespace: argocd
spec:
  metrics: # required
  - name: http-service-check # required
    initialDelay: "5s"
    interval: "5s"
    count: 1
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: http-checker
                image: alpine:3.8
                command: [sh, -c]                
                args: [echo "tests finished at $(date)" && exit -l]
              restartPolicy: Never