apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: http-check-prd
  namespace: argocd
spec:
  metrics: # required
  - name: http-check-prd # required
    initialDelay: "5s"
    interval: "5s"
    count: 3
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: http-prd
                image: filstimatias/gitops-goapp:test
                #command: [sh, -c]                
                args: ["http://my-app04-service-green-prod.production.svc.cluster.local:8080/hello", "http://my-app04-service-green-prod.production.svc.cluster.local:8080/headers"]
              restartPolicy: Never