apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app04
  template:
    metadata:
      labels:
        app: my-app04
    spec:
      containers:
      - name: my-app04
        image: filstimatias/gitops-goapp:7568ca149ab941abdce5f845cfd2dff4715cb1c0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
  strategy:
    blueGreen: 
      activeService: my-app04-service-blue
      previewService: my-app04-service-green
      prePromotionAnalysis: 
        templates: 
        - templateName: http-service-check