apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonAnnotations: 
  app01.kubernetes.prod/managed-by: mfilsti
Namespace: prod
resources:
- ../../base

patches:
- path: deployment-prod.yaml
- path: service-prod.yaml