apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
commonAnnotations: 
  app01.kubernetes.prod/managed-by: mfilsti
Namespace: staging
resources:
- ../../base

patches:
- path: deployment-staging.yaml
- path: service-staging.yaml

images:
- name: filstimatias/gitops-goapp
  newTag: 341ab719768b266ba770c2f8fff001252305a834