apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app04
spec:
  replicas: 2
  strategy:
    blueGreen: 
      prePromotionAnalysis: 
        templates: 
        - templateName: http-check-prd
          clusterScope: true