apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
commonAnnotations: 
  app01.kubernetes.prod/managed-by: mfilsti
Namespace: prod
resources:
- ../../base

patches:
- path: deployment-prod.yaml
#- path: service-prod.yaml

images:
- name: filstimatias/gitops-goapp
  newTag: 7c39684f8073b9d8484ac3e323c2f0c7edf9e761