apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod
commonAnnotations: 
  app01.kubernetes.prod/managed-by: mfilsti
Namespace: production
resources:
- ../../base

patches:
- path: deployment-prod.yaml
#- path: service-prod.yaml

images:
- name: filstimatias/gitops-goapp
  newTag: 74c904ad75b04169f8a340ee4bdfc6bb550b07f5