apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application-crd.yaml
- approject-crd.yaml
- applicationset-crd.yaml


patches:
  - target:
      kind: CustomResourceDefinition
    patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: will-be-ignored
        annotations:
          meta.helm.sh/release-name: argocd  
          meta.helm.sh/release-namespace: argocd
        labels: 
          app.kubernetes.io/managed-by: Helm